package org.camra.staffing.admin.layouts;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ViewLayout extends CssLayout {
    protected Label title;
    protected Image picture;
    protected Label role;
    protected Label comment;
    protected Button newButton;
    protected Button closeButton;
    protected Button editButton;
    protected HorizontalLayout infoHolder;
    protected CssLayout information;
    protected CssLayout gridHolder;
    protected CssLayout formHolder;
    protected CssLayout extraHolder;

    public ViewLayout() {
        Design.read(this);
    }
}
