package org.camra.staffing.ui.layouts;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.CssLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MenuLayout extends CssLayout {
    protected CssLayout menuPart;
    protected CssLayout volunteerMenuItems;
    protected CssLayout sessionMenuItems;
    protected CssLayout areaSessionMenuItems;

    public MenuLayout() {
        Design.read(this);
    }
}
