package org.camra.staffing.ui.layouts;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class VolunteerForm extends CssLayout {
    protected Label title;
    protected TextField forename;
    protected TextField surname;
    protected TextField email;
    protected TextField membership;
    protected TextField role;
    protected CheckBox firstaid;
    protected CheckBox sia;
    protected CheckBox cellar;
    protected CssLayout areaSelectorHolder;
    protected Grid areaGrid;
    protected Button save;
    protected Button cancel;
    protected Button delete;

    public VolunteerForm() {
        Design.read(this);
    }
}
